erp-order-create:
  function: create/index.js
  web: 'no'
  runtime: nodejs:22
  inputs:
    LOG_LEVEL: debug
    SENDER_IDENTITY: $SENDER_IDENTITY
    SENDER_SHARED_SECRET: $SENDER_SHARED_SECRET
    SENDER_USER_AGENT: $SENDER_USER_AGENT
    DEPLOYMENT_MODE: $DEPLOYMENT_MODE
    PAYMENT_TERM: $PAYMENT_TERM
    ERP_ENDPOINT: $ERP_ENDPOINT
    ERP_ORDER_STATUS: $ERP_ORDER_STATUS
    UNIT_OF_MEASURE: $UNIT_OF_MEASURE
    ORDER_TIME_ZONE: $ORDER_TIME_ZONE
    ORDER_ID_PREFIX: $ORDER_ID_PREFIX
    FEDEX_SHIPPING_PRODUCT_SKU: $FEDEX_SHIPPING_PRODUCT_SKU
    FEDEX_SHIPPING_PRODUCT_ID: $FEDEX_SHIPPING_PRODUCT_ID
    FEDEX_SHIPPING_PRODUCT_PRICE: $FEDEX_SHIPPING_PRODUCT_PRICE
    FEDEX_SHIPPING_PRODUCT_NAME: $FEDEX_SHIPPING_PRODUCT_NAME
    OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
    OAUTH_CLIENT_SECRETS: $OAUTH_CLIENT_SECRETS
    OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
    OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
    OAUTH_IMS_ORG_ID: $OAUTH_IMS_ORG_ID
    OAUTH_SCOPES: $OAUTH_SCOPES
    AIO_CLI_ENV: $AIO_CLI_ENV
    COMMERCE_GRAPHQL_BASE_URL: $COMMERCE_GRAPHQL_BASE_URL
    COMMERCE_BASE_URL: $COMMERCE_BASE_URL
    GW_INLINE_PRODUCT_SKU: $GW_INLINE_PRODUCT_SKU
    GW_INLINE_PRODUCT_NAME: $GW_INLINE_PRODUCT_NAME
    GW_INLINE_PRODUCT_ID: $GW_INLINE_PRODUCT_ID
    GW_INLINE_PRODUCT_PRICE: $GW_INLINE_PRODUCT_PRICE
    GW_INLINE_PRODUCT_QUANTITY: $GW_INLINE_PRODUCT_QUANTITY
    GW_INLINE_BUNDLE_PRODUCT_SKU: $GW_INLINE_BUNDLE_PRODUCT_SKU
    GW_INLINE_BUNDLE_PRODUCT_NAME: $GW_INLINE_BUNDLE_PRODUCT_NAME
    GW_INLINE_BUNDLE_PRODUCT_ID: $GW_INLINE_BUNDLE_PRODUCT_ID
    GW_INLINE_BUNDLE_PRODUCT_PRICE: $GW_INLINE_BUNDLE_PRODUCT_PRICE
    GW_INLINE_GIFT_NOTE_PRODUCT_SKU: $GW_INLINE_GIFT_NOTE_PRODUCT_SKU
    GW_INLINE_GIFT_NOTE_PRODUCT_NAME: $GW_INLINE_GIFT_NOTE_PRODUCT_NAME
    GW_INLINE_GIFT_NOTE_PRODUCT_ID: $GW_INLINE_GIFT_NOTE_PRODUCT_ID
    GW_INLINE_GIFT_NOTE_PRODUCT_PRICE: $GW_INLINE_GIFT_NOTE_PRODUCT_PRICE
    FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_SKU: $FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_SKU
    FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_NAME: $FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_NAME
    FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_ID: $FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_ID
    FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_PRICE: $FEDEX_INTERNATIONAL_SHIPPING_PRODUCT_PRICE
    GIFT_CARD_PRODUCT_SKU: $GIFT_CARD_PRODUCT_SKU
    GIFT_CARD_PRODUCT_NAME: $GIFT_CARD_PRODUCT_NAME
    ERP_LOG: $ERP_LOG
    PROMO_CODE_LINE_ITEM_SKU: $PROMO_CODE_LINE_ITEM_SKU
    PROMO_CODE_LINE_ITEM_NAME: $PROMO_CODE_LINE_ITEM_NAME
  annotations:
    require-adobe-auth: false
    final: true
