name: AIO App CI/CD Test

on:
  push:
    branches:
      - stage
jobs:
  deploy:
    name: Deploy to Stage
    environment: stage
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['22']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Debug - Node Info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Debug - Validate Scopes Format
        run: |
          echo "Validating SCOPES format..."
          SCOPES="${{ secrets.SCOPES_STAGE }}"
          
          # Check if scopes match the required pattern
          if echo "$SCOPES" | grep -qE '^[0-9a-zA-Z_.s]+(,[0-9a-zA-Z_.s]+)*$'; then
            echo "✅ SCOPES format is valid"
            echo "✅ Length: $(echo -n "$SCOPES" | wc -c) characters"
            echo "✅ No spaces detected"
          else
            echo "❌ SCOPES format is INVALID"
            echo "❌ Expected pattern: ^[0-9a-zA-Z_.s]+(,[0-9a-zA-Z_.s]+)*$"
            
            # Check for common issues
            if echo "$SCOPES" | grep -q ' '; then
              echo "❌ Contains spaces"
            fi
            if echo "$SCOPES" | grep -q '\['; then
              echo "❌ Contains array brackets"
            fi
            if echo "$SCOPES" | grep -q '"'; then
              echo "❌ Contains quotes"
            fi
            
            exit 1
          fi
      - name: Auth
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: oauth_sts
          CLIENTID: ${{ secrets.CLIENTID_STAGE }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET_STAGE }}
          TECHNICALACCOUNTID: ${{ secrets.TECHNICALACCID_STAGE }}
          TECHNICALACCOUNTEMAIL: ${{ secrets.TECHNICALACCEMAIL_STAGE }}
          IMSORGID: ${{ secrets.IMSORGID_STAGE }}
          SCOPES: ${{ secrets.SCOPES_STAGE }}
      # - name: Build
      #   env:
      #     AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
      #   uses: adobe/aio-apps-action@3.3.0
      #   with:
      #     os: ${{ matrix.os }}
      #     command: build
      # - name: Deploy
      #   env:
      #     AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE_STAGE }}
      #     AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_STAGE }}
          # AIO_PROJECT_ID: ${{ secrets.AIO_PROJECT_ID_STAGE }}
          # AIO_PROJECT_NAME: ${{ secrets.AIO_PROJECT_NAME_STAGE }}
          # AIO_PROJECT_ORG_ID: ${{ secrets.AIO_PROJECT_ORG_ID_STAGE }}
          # AIO_PROJECT_WORKSPACE_ID: ${{ secrets.AIO_PROJECT_WORKSPACE_ID_STAGE }}
          # AIO_PROJECT_WORKSPACE_NAME: ${{ secrets.AIO_PROJECT_WORKSPACE_NAME_STAGE }}
          # AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ secrets.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES_STAGE }}
        # uses: adobe/aio-apps-action@3.3.0
        # with:
        #   os: ${{ matrix.os }}
        #   command: deploy
        #   noPublish: true