name: AIO App CI/CD Test

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Prod
    environment: prod
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ['22']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Debug - Node Info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
      - name: Check ENV
        run: echo "This is Prod"
